## About dataset

### Name: Black Friday Retail Sales Analysis

The dataset represents Black Friday retail transactions collected from a retail business during festive sale periods.

Each row corresponds to a single customer transaction.

Primary objective:
1. Understand customer purchasing behavior
2. Identify profitable products and customer segments
3. Optimize marketing campaigns
4. Detect high-value customers

In [1]:
# Importing libraries

import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("../datasets/retail_black_friday_sales_100k.csv")
df.head(5)

,transaction_id,customer_id,age_group,gender,city,customer_segment,product_id,product_category,original_price,discount_pct,final_price,quantity,purchase_amount,payment_method,purchase_date,purchase_hour,is_weekend,is_black_friday
0,T0000001,C007297,26-35,Male,San Francisco,Loyal,P2713,Footwear,153.73,35,99.92,1,99.92,Credit Card,2025-12-01,0,0,0
1,T0000002,C001640,56+,Other,Dallas,Returning,P7219,Beauty,230.05,40,138.03,1,138.03,PayPal,2025-11-24,5,0,0
2,T0000003,C018025,26-35,Male,Phoenix,New,P5521,Groceries,174.67,25,131.00,1,131.00,Credit Card,2025-11-24,14,0,0
3,T0000004,C016050,18-25,Other,Miami,VIP,P3003,Sports,399.61,40,239.77,1,239.77,Credit Card,2025-11-30,23,1,0
4,T0000005,C014629,46-55,Male,Los Angeles,Loyal,P4633,Footwear,120.87,30,84.61,2,169.22,Debit Card,2025-11-25,2,0,0

In [ ]:
# Structural Integrety check

print(df.shape, '\n')
print(df.dtypes, '\n')
print(df.info(), '\n')

(100000, 18)

transaction_id       object
customer_id          object
age_group            object
gender               object
city                 object
customer_segment     object
product_id           object
product_category     object
original_price      float64
discount_pct          int64
final_price         float64
quantity              int64
purchase_amount     float64
payment_method       object
purchase_date        object
purchase_hour         int64
is_weekend            int64
is_black_friday       int64
dtype: object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    100000 non-null  object
 1   customer_id       100000 non-null  object
 2   age_group         100000 non-null  object
 3   gender            100000 non-null  object
 4   city              100000 non-null  object
 5   customer_segment  100000 non-null  object
 6   product_id        100000 non-null  object
 7   product_category  100000 non-null  object
 8   original_price    100000 non-null  float64
 9   discount_pct      100000 non-null  int64
 10  final_price       100000 non-null  float64
 11  quantity          100000 non-null  int64
 12  purchase_amount   100000 non-null  float64
 13  payment_method    100000 non-null  object
 14  purchase_date     100000 non-null  object
 15  purchase_hour     100000 non-null  int64
 16  is_weekend        100000 non-null  int64
 17  is_black_friday   100000 non-null  int64
dtypes: float64(3), int64(5), object(10)
memory usage: 13.7+ MB
None

       original_price   discount_pct    final_price       quantity  \
count   100000.000000  100000.000000  100000.000000  100000.000000
mean       330.281911      26.631150     242.220661       1.447290
std        444.315916      12.249229     332.677331       0.815762
min          5.000000       5.000000       2.070000       1.000000
25%         88.117500      20.000000      62.940000       1.000000
50%        180.220000      25.000000     129.490000       1.000000
75%        333.712500      35.000000     247.575000       2.000000
max       2499.890000      60.000000    2374.900000       5.000000

       purchase_amount  purchase_hour     is_weekend  is_black_friday
count    100000.000000  100000.000000  100000.000000    100000.000000
mean        351.256307      11.482240       0.248110         0.126330
std         589.856777       6.912777       0.431918         0.332223
min           2.220000       0.000000       0.000000         0.000000
25%          75.750000       5.000000       0.000000         0.000000
50%         161.150000      11.000000       0.000000         0.000000
75%         358.722500      17.000000       0.000000         0.000000
max       11441.800000      23.000000       1.000000         1.000000

In [9]:
df.describe()

,original_price,discount_pct,final_price,quantity,purchase_amount,purchase_hour,is_weekend,is_black_friday
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,330.281911,26.631150,242.220661,1.447290,351.256307,11.482240,0.248110,0.126330
std,444.315916,12.249229,332.677331,0.815762,589.856777,6.912777,0.431918,0.332223
min,5.000000,5.000000,2.070000,1.000000,2.220000,0.000000,0.000000,0.000000
25%,88.117500,20.000000,62.940000,1.000000,75.750000,5.000000,0.000000,0.000000
50%,180.220000,25.000000,129.490000,1.000000,161.150000,11.000000,0.000000,0.000000
75%,333.712500,35.000000,247.575000,2.000000,358.722500,17.000000,0.000000,0.000000
max,2499.890000,60.000000,2374.900000,5.000000,11441.800000,23.000000,1.000000,1.000000

In [11]:
# Missing values check

print(df.isnull().sum(), '\n')

transaction_id      0
customer_id         0
age_group           0
gender              0
city                0
customer_segment    0
product_id          0
product_category    0
original_price      0
discount_pct        0
final_price         0
quantity            0
purchase_amount     0
payment_method      0
purchase_date       0
purchase_hour       0
is_weekend          0
is_black_friday     0
dtype: int64

In [14]:
# Duplicate Detection 
df.duplicated().sum()

np.int64(0)

### Note: No NULL values and no Duplicate values detected in the dataset.

In [ ]:
# Type conversions

df['original_price'] = df['original_price'].astype('float64')
df['discount_pct'] = df['discount_pct'].astype('float64')
df['final_price'] = df['final_price'].astype('float64')
df['quantity'] = df['quantity'].astype('int64')
df['customer_id'] = df['customer_id'].astype('str')
df['transaction_id'] = df['transaction_id'].astype('str')
df['product_id'] = df['product_id'].astype('str')
df["purchase_date"] = pd.to_datetime(df["purchase_date"])

df.dtypes

transaction_id              object
customer_id                 object
age_group                   object
gender                      object
city                        object
customer_segment            object
product_id                  object
product_category            object
original_price             float64
discount_pct               float64
final_price                float64
quantity                     int64
purchase_amount            float64
payment_method              object
purchase_date       datetime64[ns]
purchase_hour                int64
is_weekend                   int64
is_black_friday              int64
dtype: object

In [24]:
calculated_price = (df["original_price"] * (1 - df["discount_pct"] / 100)).round(2)

calculated_purchase = (df["final_price"] * df["quantity"]).round(2)
invalid_purchase = df[calculated_purchase != df["purchase_amount"]]
print(len(invalid_purchase))

0

In [29]:
#Date metadata extraction
df["year"] = df["purchase_date"].dt.year
df["month"] = df["purchase_date"].dt.month
df["day"] = df["purchase_date"].dt.day
df["day_name"] = df["purchase_date"].dt.day_name()

def categorize_hour(hour):
    if 0 <= hour < 6:
        return "Late Night"

    if 6 <= hour < 12:
        return "Morning"

    if 12 <= hour < 18:
        return "Afternoon"

    return "Evening"


df["time_slot"] = df["purchase_hour"].apply(categorize_hour)

In [30]:
df.head(6)

,transaction_id,customer_id,age_group,gender,city,customer_segment,product_id,product_category,original_price,discount_pct,...,payment_method,purchase_date,purchase_hour,is_weekend,is_black_friday,year,month,day,day_name,time_slot
0,T0000001,C007297,26-35,Male,San Francisco,Loyal,P2713,Footwear,153.73,35.0,...,Credit Card,2025-12-01,0,0,0,2025,12,1,Monday,Late Night
1,T0000002,C001640,56+,Other,Dallas,Returning,P7219,Beauty,230.05,40.0,...,PayPal,2025-11-24,5,0,0,2025,11,24,Monday,Late Night
2,T0000003,C018025,26-35,Male,Phoenix,New,P5521,Groceries,174.67,25.0,...,Credit Card,2025-11-24,14,0,0,2025,11,24,Monday,Afternoon
3,T0000004,C016050,18-25,Other,Miami,VIP,P3003,Sports,399.61,40.0,...,Credit Card,2025-11-30,23,1,0,2025,11,30,Sunday,Evening
4,T0000005,C014629,46-55,Male,Los Angeles,Loyal,P4633,Footwear,120.87,30.0,...,Debit Card,2025-11-25,2,0,0,2025,11,25,Tuesday,Late Night
5,T0000006,C009145,46-55,Other,Seattle,Returning,P4013,Accessories,192.91,40.0,...,Gift Card,2025-12-01,17,0,0,2025,12,1,Monday,Afternoon

In [32]:
customer_spending = (
    df.groupby("customer_id")["purchase_amount"]
    .sum()
    .reset_index()
)

customer_spending.rename(
    columns={
        "purchase_amount":
        "total_customer_spending"
    },
    inplace=True
)

customer_spending.head()

  customer_id  total_customer_spending
0     C000001                   354.65
1     C000003                   457.02
2     C000004                  1023.37
3     C000005                  1597.88
4     C000006                  1337.85

In [31]:
Q1 = df["purchase_amount"].quantile(0.25)
Q3 = df["purchase_amount"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[
    (df["purchase_amount"] < lower) |
    (df["purchase_amount"] > upper)
]

outliers.shape

(10897, 23)

## Data Analysis

### 1. customer purchase analysis

In [41]:
#total revenue
print(f"Total Revenue: {df['purchase_amount'].sum()}") 

#Avg transaction value
print(f"Average Transaction Value: {df["purchase_amount"].mean()}")

print(f"Customer Count: {df["customer_id"].nunique()}")

top_customers = (df.groupby("customer_id")["purchase_amount"].sum().sort_values(ascending=False).head(10))
print(f"Top 10 Customers: \n{top_customers}")

Total Revenue: 35125630.67
Average Transaction Value: 351.25630670000004
Customer Count: 32997
Top 10 Customers:
customer_id
C012695    14057.64
C013072    13654.03
C028692    13207.78
C031820    12449.42
C001139    11871.52
C019630    11710.95
C032035    10946.64
C006465    10847.62
C024872    10815.89
C004610    10569.15
Name: purchase_amount, dtype: float64

### 2. Profitable product, age based and gender based spendings

In [55]:
category_sales = (df.groupby("product_category")["purchase_amount"].sum().sort_values(ascending=False))

category_sales

product_category
Electronics       14123441.47
Home & Kitchen     6461099.92
Sports             3303563.29
Accessories        2754561.54
Footwear           2013317.39
Clothing           1688471.88
Toys               1669209.91
Beauty             1374751.97
Groceries          1075986.12
Books               661227.18
Name: purchase_amount, dtype: float64

In [ ]:
gender_sales = df.groupby("gender")["purchase_amount"].sum().sort_values(ascending=False)
gender_sales

gender
Male      11767285.96
Other     11719413.02
Female    11638931.69
Name: purchase_amount, dtype: float64

In [57]:
age_sales = df.groupby("age_group")["purchase_amount"].sum().sort_values(ascending=False)

age_sales

age_group
36-45    7196872.71
18-25    7051066.02
26-35    7021938.74
46-55    7014278.85
56+      6841474.35
Name: purchase_amount, dtype: float64

### 3. City sales and Segment-wise revenue

In [59]:
city_sales = df.groupby("city")["purchase_amount"].sum().sort_values(ascending=False)
city_sales

city
Atlanta          3618348.52
Miami            3566829.80
Dallas           3547967.43
New York         3546500.70
Phoenix          3526014.43
Chicago          3512360.63
Houston          3474957.45
Seattle          3456842.39
San Francisco    3445376.30
Los Angeles      3430433.02
Name: purchase_amount, dtype: float64

In [61]:
segment_sales = df.groupby("customer_segment")["purchase_amount"].sum()
segment_sales

customer_segment
Loyal         8888416.70
New          10574443.42
Returning    12125507.74
VIP           3537262.81
Name: purchase_amount, dtype: float64

### 4. High Value Customers

In [63]:
customer_spending = df.groupby("customer_id")["purchase_amount"].sum().reset_index()

thresh = customer_spending["purchase_amount"].quantile(0.99)
high_value = customer_spending[customer_spending["purchase_amount"] > thresh]

high_value

      customer_id  purchase_amount
266       C000281          7214.22
368       C000391          5831.09
488       C000521          6142.49
574       C000610          7608.36
745       C000787          6609.64
...           ...              ...
32295     C034258          6315.44
32415     C034384          5976.90
32711     C034698          8470.04
32819     C034813          6257.58
32964     C034967          7310.52

[330 rows x 2 columns]

In [65]:
# Correlation analysis 
numeric_df = df.select_dtypes(include=np.number)
df_corr = numeric_df.corr()
df_corr

,original_price,discount_pct,final_price,quantity,purchase_amount,purchase_hour,is_weekend,is_black_friday,year,month,day
original_price,1.000000,0.001899,0.979184,0.001643,0.802254,-0.000256,0.003381,-0.001729,NaN,0.001177,-0.000476
discount_pct,0.001899,1.000000,-0.119105,0.002567,-0.100206,-0.006005,-0.000152,0.000218,NaN,-0.004684,0.004190
final_price,0.979184,-0.119105,1.000000,0.002553,0.821721,-0.000026,0.003208,-0.002281,NaN,0.002057,-0.001331
quantity,0.001643,0.002567,0.002553,1.000000,0.336325,0.002899,-0.001865,-0.000060,NaN,0.002740,-0.002970
purchase_amount,0.802254,-0.100206,0.821721,0.336325,1.000000,0.003281,0.003355,-0.002801,NaN,0.002050,-0.001368
purchase_hour,-0.000256,-0.006005,-0.000026,0.002899,0.003281,1.000000,0.003511,0.002203,NaN,0.000340,0.000794
is_weekend,0.003381,-0.000152,0.003208,-0.001865,0.003355,0.003511,1.000000,-0.218436,NaN,-0.216631,0.375197
is_black_friday,-0.001729,0.000218,-0.002281,-0.000060,-0.002801,0.002203,-0.218436,1.000000,NaN,-0.143402,0.183446
year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
month,0.001177,-0.004684,0.002057,0.002740,0.002050,0.000340,-0.216631,-0.143402,NaN,1.000000,-0.977184
day,-0.000476,0.004190,-0.001331,-0.002970,-0.001368,0.000794,0.375197,0.183446,NaN,-0.977184,1.000000